package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/markbates/pop"
	"github.com/marythought/bolt/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Campaign)
// DB Table: Plural (Campaigns)
// Resource: Plural (Campaigns)
// Path: Plural (/campaigns)
// View Template Folder: Plural (/templates/campaigns/)

// CampaignsResource is the resource for the campaign model
type CampaignsResource struct {
	buffalo.Resource
}

// List gets all Campaigns. This function is mapped to the the path
// GET /campaigns
func (v CampaignsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	campaigns := &models.Campaigns{}
	// You can order your list here. Just change
	err := tx.All(campaigns)
	// to:
	// err := tx.Order("(case when completed then 1 else 2 end) desc, lower([sort_parameter]) asc").All(campaigns)
	// Don't forget to change [sort_parameter] to the parameter of
	// your model, which should be used for sorting.
	if err != nil {
		return err
	}
	// Make campaigns available inside the html template
	c.Set("campaigns", campaigns)
	return c.Render(200, r.HTML("campaigns/index.html"))
}

// Show gets the data for one Campaign. This function is mapped to
// the path GET /campaigns/{campaign_id}
func (v CampaignsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Campaign
	campaign := &models.Campaign{}
	// To find the Campaign the parameter campaign_id is used.
	err := tx.Find(campaign, c.Param("campaign_id"))
	if err != nil {
		return err
	}
	// Make campaign available inside the html template
	c.Set("campaign", campaign)
	return c.Render(200, r.HTML("campaigns/show.html"))
}

// New renders the formular for creating a new campaign.
// This function is mapped to the path GET /campaigns/new
func (v CampaignsResource) New(c buffalo.Context) error {
	// Make campaign available inside the html template
	c.Set("campaign", &models.Campaign{})
	return c.Render(200, r.HTML("campaigns/new.html"))
}

// Create adds a campaign to the DB. This function is mapped to the
// path POST /campaigns
func (v CampaignsResource) Create(c buffalo.Context) error {
	// Allocate an empty Campaign
	campaign := &models.Campaign{}
	// Bind campaign to the html form elements
	err := c.Bind(campaign)
	if err != nil {
		return err
	}
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(campaign)
	if err != nil {
		return err
	}
	if verrs.HasAny() {
		// Make campaign available inside the html template
		c.Set("campaign", campaign)
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("campaigns/new.html"))
	}
	// If there are no errors set a success message
	c.Flash().Add("success", "Campaign was created successfully")
	// and redirect to the campaigns index page
	return c.Redirect(302, "/campaigns/%s", campaign.ID)
}

// Edit renders a edit formular for a campaign. This function is
// mapped to the path GET /campaigns/{campaign_id}/edit
func (v CampaignsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Campaign
	campaign := &models.Campaign{}
	err := tx.Find(campaign, c.Param("campaign_id"))
	if err != nil {
		return err
	}
	// Make campaign available inside the html template
	c.Set("campaign", campaign)
	return c.Render(200, r.HTML("campaigns/edit.html"))
}

// Update changes a campaign in the DB. This function is mapped to
// the path PUT /campaigns/{campaign_id}
func (v CampaignsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Campaign
	campaign := &models.Campaign{}
	err := tx.Find(campaign, c.Param("campaign_id"))
	if err != nil {
		return err
	}
	// Bind campaign to the html form elements
	err = c.Bind(campaign)
	if err != nil {
		return err
	}
	verrs, err := tx.ValidateAndUpdate(campaign)
	if err != nil {
		return err
	}
	if verrs.HasAny() {
		// Make campaign available inside the html template
		c.Set("campaign", campaign)
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("campaigns/edit.html"))
	}
	// If there are no errors set a success message
	c.Flash().Add("success", "Campaign was updated successfully")
	// and redirect to the campaigns index page
	return c.Redirect(302, "/campaigns/%s", campaign.ID)
}

// Destroy deletes a campaign from the DB. This function is mapped
// to the path DELETE /campaigns/{campaign_id}
func (v CampaignsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Campaign
	campaign := &models.Campaign{}
	// To find the Campaign the parameter campaign_id is used.
	err := tx.Find(campaign, c.Param("campaign_id"))
	if err != nil {
		return err
	}
	err = tx.Destroy(campaign)
	if err != nil {
		return err
	}
	// If there are no errors set a flash message
	c.Flash().Add("success", "Campaign was destroyed successfully")
	// Redirect to the campaigns index page
	return c.Redirect(302, "/campaigns")
}
